version: "3.5"
services:
  mysql: # Database
    container_name: mysql
    image: mysql:latest
    command: mysqld --datadir=/tmp/mysqldata
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fleet
      MYSQL_USER: fleet
      MYSQL_PASSWORD: toor
    volumes:
      - mysqldata:/tmp:rw
    restart: unless-stopped

  redis: # Database
    container_name: redis
    image: redis:latest
    restart: unless-stopped

  fleet: # Fleet webserver/binary
    container_name: fleet
    image: fleetdm/fleet:latest
    command: sh -c "echo '\n' | /usr/bin/fleet prepare db --config=/tmp/fleet.yml && /usr/bin/fleet serve --config=/tmp/fleet.yml"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./quick-fleet/:/tmp
    ports:
      - "8443:443"
    restart: unless-stopped

volumes:
  mysqldata:
